In [2]:
import quaternion, os
import numpy as np
import torch
from torch.nn import functional as F

In [4]:
path1 = "/media/fangxu/Disk4T/LQ/data/chess/seq-01/frame-000800.pose.txt"
pose = np.loadtxt( path1 )
q =  quaternion.from_rotation_matrix(pose[:3,:3] )
q_arr = quaternion.as_float_array(q)
print(q_arr)

[ 0.92052049 -0.24653781  0.30157997  0.03017701]


In [28]:
t1 = torch.randn(2,4)
t2 = torch.randn(2,4)


In [32]:
dd =torch.mul(t1,t2)
dd

tensor([[-0.9324, -0.1744,  0.4602, -0.1457],
        [-0.7585,  0.0866, -1.2343,  1.1070]])

In [31]:
t1*t2

tensor([[-0.9324, -0.1744,  0.4602, -0.1457],
        [-0.7585,  0.0866, -1.2343,  1.1070]])

In [86]:
dd[dd>1.0] = 1.0

In [94]:
isinstance(t1.numpy(),np.ndarray)

True

In [109]:
ww = torch.tensor([0.3440,  0.6696])
torch.acos(ww)

tensor([1.2196, 0.8371])

In [111]:
np.arccos(ww.numpy())
np.pi

3.141592653589793

In [108]:
np.dot( t1.numpy()[0], t2.numpy()[0] )

-2.8785138

In [93]:
type(t1.numpy())

numpy.ndarray

In [12]:
torch.from_numpy(q_arr).to(torch.float32).shape

torch.Size([4])

In [7]:
torch.norm(torch.from_numpy(q_arr))

tensor(1., dtype=torch.float64)

In [9]:
round(123.12334555,4)

123.1233

In [24]:
pdist = torch.nn.PairwiseDistance(2)
input1 = torch.randn(4,5)
input2 = torch.randn(4,5)

In [25]:
d1 = pdist(input1,input2)
print(list(d1.numpy()))

[3.2484925, 2.6367738, 5.224956, 3.7721436]


In [18]:
F.mse_loss(input1[1],input2[1])*5

tensor(13.3813)

In [21]:
import math
math.sqrt(13.3813)

3.6580459264476164

In [28]:
math.sqrt(1.0693*5)

2.312249986485025

In [1]:
list( d1.numpy()) +list(d1)

NameError: name 'd1' is not defined

In [46]:
d2 = list( d1)

d2.sort()

In [47]:
d2

[tensor(2.2590),
 tensor(2.7179),
 tensor(3.2925),
 tensor(3.9273),
 tensor(4.9686)]

In [49]:
list( d1.numpy() )

[2.2590034, 3.927343, 3.2925403, 4.9686356, 2.71789]

In [52]:
d3 = d1.cuda()


In [27]:
list(d1.cpu().numpy())

[3.2484925, 2.6367738, 5.224956, 3.7721436]