In [1]:
import quaternion, os
import numpy as np
import torch
from torch.nn import functional as F

In [2]:
path1 = "/media/fangxu/Disk4T/LQ/data/chess/seq-01/frame-000800.pose.txt"
pose = np.loadtxt( path1 )
q =  quaternion.from_rotation_matrix(pose[:3,:3] )
q_arr = quaternion.as_float_array(q)
print(q_arr)

[ 0.92052049 -0.24653781  0.30157997  0.03017701]


In [54]:
t1 = torch.randn(2,4)
t2 = torch.randn(2,4)


In [55]:
dd =torch.mul(t1,t2)
dd

tensor([[-0.4470,  0.8252,  0.3616,  0.0939],
        [ 1.4599,  0.3419, -0.0020,  1.2974]])

In [17]:
t1*t2

tensor([[-0.5019,  0.2649, -0.0058,  0.3880],
        [-0.1392,  1.6300, -1.0722,  0.7108]])

In [86]:
dd[dd>1.0] = 1.0

In [15]:
t1

tensor([[-0.5152, -0.1947,  0.5553, -0.2789],
        [ 0.0801, -1.0403, -0.7495,  0.7092]])

In [16]:
t2

tensor([[ 0.9742, -1.3604, -0.0104, -1.3909],
        [-1.7378, -1.5668,  1.4305,  1.0023]])

In [20]:
1.4305 * -0.7495

-1.0721597500000002

In [56]:
def quaternion_angular_error(q1,q2):
    d = torch.abs(torch.mul(q1,q2).sum(1)  )
    d[d>1.0] = 1.0
    theta = 2* torch.acos( d ) * 180.0 /np.pi
    return theta

In [57]:
quaternion_angular_error(t1,t2)

tensor([67.0451,  0.0000])

In [21]:
torch.mul(t1,t2).sum(1)

tensor([0.1451, 1.1293])

In [46]:
def quaternion_angular_error2(q1, q2):
    d = abs(np.dot(q1, q2))
    d = min(1.0, max(-1.0, d))
    theta = 2 * np.arccos(d) * 180 / np.pi
    return theta

In [58]:
quaternion_angular_error2(t1.numpy()[0], t2.numpy()[0])

67.04513689284516

In [94]:
isinstance(t1.numpy(),np.ndarray)

True

In [109]:
ww = torch.tensor([0.3440,  0.6696])
torch.acos(ww)

tensor([1.2196, 0.8371])

In [111]:
np.arccos(ww.numpy())
np.pi

3.141592653589793

In [108]:
np.dot( t1.numpy()[0], t2.numpy()[0] )

-2.8785138

In [93]:
type(t1.numpy())

numpy.ndarray

In [12]:
torch.from_numpy(q_arr).to(torch.float32).shape

torch.Size([4])

In [7]:
torch.norm(torch.from_numpy(q_arr))

tensor(1., dtype=torch.float64)

In [9]:
round(123.12334555,4)

123.1233

In [24]:
pdist = torch.nn.PairwiseDistance(2)
input1 = torch.randn(4,5)
input2 = torch.randn(4,5)

In [25]:
d1 = pdist(input1,input2)
print(list(d1.numpy()))

[3.2484925, 2.6367738, 5.224956, 3.7721436]


In [18]:
F.mse_loss(input1[1],input2[1])*5

tensor(13.3813)

In [21]:
import math
math.sqrt(13.3813)

3.6580459264476164

In [28]:
math.sqrt(1.0693*5)

2.312249986485025

In [1]:
list( d1.numpy()) +list(d1)

NameError: name 'd1' is not defined

In [46]:
d2 = list( d1)

d2.sort()

In [47]:
d2

[tensor(2.2590),
 tensor(2.7179),
 tensor(3.2925),
 tensor(3.9273),
 tensor(4.9686)]

In [49]:
list( d1.numpy() )

[2.2590034, 3.927343, 3.2925403, 4.9686356, 2.71789]

In [52]:
d3 = d1.cuda()


In [27]:
list(d1.cpu().numpy())

[3.2484925, 2.6367738, 5.224956, 3.7721436]