In [18]:
import mmcv
from mmcv import Config
import open3d
import numpy as np
import torch
import MinkowskiEngine as ME
import numpy as np


points = np.random.random(size=(1000,3))

tt = torch.tensor(points,dtype=torch.float)
tt.type(torch.float)[9]

tensor([0.7379, 0.9833, 0.7144])

In [11]:
def get_coords(data):
    coords = []
    for i, row in enumerate(data):
        for j, col in enumerate(row):
            if col != " ":
                coords.append([i, j])
    return np.array(coords)

def data_loader(
    nchannel=3,
    max_label=5,
    is_classification=True,
    seed=-1,
    batch_size=2,
    dtype=torch.float32,
):
    if seed >= 0:
        torch.manual_seed(seed)

    data = ["   X   ", "  X X  ", " XXXXX "]

    # Generate coordinates
    coords = [get_coords(data) for i in range(batch_size)]
    coords = ME.utils.batched_coordinates(coords)

    # features and labels
    N = len(coords)
    feats = torch.arange(N * nchannel).view(N, nchannel).to(dtype)
    label = (torch.rand(batch_size if is_classification else N) * max_label).long()
    return coords, feats, label


In [12]:
path = "/media/fangxu/Disk4T/fangxuPrj/Depth_Point_Location_Attention/config/conf_1.py"
cfg = Config.fromfile(path)
print(cfg.learning_rate)
#print(cfg.cuda)

pcd_path = "/media/fangxu/Disk4T/LQ/pointcloud/chess/seq-01/frame-000363.cloud.ply"
pcd_data =  open3d.io.read_point_cloud(pcd_path)
print(pcd_data.points)

voxel_data = pcd_data.voxel_down_sample(voxel_size= 0.01)
print(voxel_data.points)

0.0001
std::vector<Eigen::Vector3d> with 307200 elements.
Use numpy.asarray() to access data.
std::vector<Eigen::Vector3d> with 84408 elements.
Use numpy.asarray() to access data.


In [13]:
coords, feats, labels = data_loader(nchannel=1)
print(coords.shape)
print(feats.shape)
print(labels.shape)

torch.Size([16, 3])
torch.Size([16, 1])
torch.Size([2])


In [9]:
z

True

std::vector<Eigen::Vector3d> with 307200 elements.
Use numpy.asarray() to access data.

std::vector<Eigen::Vector3d> with 84408 elements.
Use numpy.asarray() to access data.

In [35]:
import configparser

config = configparser.ConfigParser()
config.read("/media/fangxu/Disk4T/fangxuPrj/MinkLoc3D/config/config_baseline.txt")
params = config['DEFAULT']
num_points = params.getint('num_points', 4096)


In [38]:
params = config['TRAIN']
num_workers = params.getint('num_workers',7)
dataset_folder = params.get ('seq_train_list')
print(list(dataset_folder))
print(num_workers )
print(type(dataset_folder))

['[', '1', ',', '2', ',', '3', ',', '4', ']']
7
<class 'str'>


In [17]:
np.asarray(voxel_data.points).shape

(72228, 3)

In [3]:
import spconv
import torch

features = torch.randn(1000,3)

indices = torch.randn(1000,4)
spatial_shape=(200,3)
batch_size=5
x = spconv.SparseConvTensor(features, indices, spatial_shape, batch_size)


In [37]:
x_dense_NCHW = x.dense() # convert sparse tensor to dense NCHW tensor.
print(x.sparity) 

IndexError: index 3 is out of bounds for dimension 2 with size 3

In [41]:
 from spconv.utils import VoxelGeneratorV2 as VoxelGenerator

In [48]:
voxel_generator = VoxelGenerator(
                voxel_size=  [0.05, 0.05, 0.1] , #config.VOXEL_SIZE,
                point_cloud_range=[0, -40, -3, 70.4, 40, 1], #self.point_cloud_range,
                max_num_points=5, #config.MAX_POINTS_PER_VOXEL,
                max_voxels=160000 #config.MAX_NUMBER_OF_VOXELS[self.mode]
            )

In [42]:
p = np.random.randn(100,3)

In [45]:
p1 = p[:,0:1]
p2 = p[:,0:1]
p3 = p[:,0:1]

In [46]:
pp = np.concatenate([p1,p2,p3],axis =1)

In [47]:
pp.shape

(100, 3)

In [25]:
import spconv
import torch
import numpy as np
voxel_generator = spconv.utils.VoxelGenerator(
    voxel_size=[0.1, 0.1, 0.1], 
    point_cloud_range=[-50, -50, -3, 50, 50, 1],
    max_num_points=30,
    max_voxels=40000,
    full_mean=False
)

points =np.asarray(pcd_data.points) # [N, 3+] tensor.
points = np.random.randn(1000,3)
voxels, coords, num_points_per_voxel = voxel_generator.generate(points)

In [26]:
voxels.shape

(376, 30, 3)

In [55]:
np.asarray(pcd_data.points)

array([[-1.1424, -0.7321,  0.8806],
       [-1.1269, -0.7356,  0.8764],
       [-1.1244, -0.7369,  0.8785],
       ...,
       [ 1.0745, -1.0865, -0.1665],
       [ 1.0745, -1.0865, -0.1665],
       [ 1.0745, -1.0865, -0.1665]])

In [58]:
voxels = np.zeros(shape=(1,2), dtype=points.dtype)

TypeError: Cannot interpret 'torch.float64' as a data type

In [20]:
points = np.random.randn(100,3)

In [27]:
376*30

11280

In [33]:
coords.shape

(376, 3)

In [30]:
num_points_per_voxel.shape

(376,)

In [41]:
import torch
import spconv
from spconv.test_utils import TestCase, generate_sparse_data, params_grid
import numpy as np 
# convert a NDHW C dense tensor to sparse:
# first we generate 3d fake data with 32 features and batch size 2
sparse_dict = generate_sparse_data([50, 30, 30], [1000, 1000], 32)
features = np.ascontiguousarray(sparse_dict["features"]).astype(
    np.float32)

In [37]:
sparse_dict['features'].shape

(2000, 32)

In [40]:
sparse_dict['features_dense'].shape

(2, 32, 50, 30, 30)

torch.Size([16, 3])
torch.Size([16, 1])
torch.Size([2])


In [28]:
labels

tensor([4, 1])

In [37]:
feats

tensor([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.]])

In [56]:
# data = [
#     [0, 0, 2.1, 0, 0],
#     [0, 1, 1.4, 3, 0],
#     [0, 0, 4.0, 0, 0]
# ]
data = np.asarray( voxel_data.points )


In [61]:
def to_sparse_coo(data):
    # An intuitive way to extract coordinates and features
    coords, feats = [], []
    for i, row in enumerate(data):
        for j, val in enumerate(row):
            if val != 0:
                coords.append([i, j])
                feats.append([val])
    return torch.IntTensor(coords), torch.FloatTensor(feats)

coords , feats =to_sparse_coo(data)

In [58]:
coods.shape

torch.Size([253223, 2])

In [59]:
feat.shape

torch.Size([253223, 1])

In [62]:
A = ME.SparseTensor(coordinates=coords, features=feats)

SparseTensor(
  coordinates=tensor([[    0,     0],
        [    0,     1],
        [    0,     2],
        ...,
        [84407,     0],
        [84407,     1],
        [84407,     2]], dtype=torch.int32)
  features=tensor([[ 1.2983],
        [-0.0454],
        [ 2.3938],
        ...,
        [ 1.0284],
        [-0.6577],
        [ 1.7524]])
  coordinate_map_key=coordinate map key:[1]
  coordinate_manager=CoordinateMapManagerCPU(
	[1, ]:	CoordinateMapCPU:253223x2
	algorithm=MinkowskiAlgorithm.DEFAULT
  )
  spatial dimension=1)